// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: C:/Users/USER/Desktop/Compiler Project/ProjectFiles/src/Scanner.flex

// user code
// mesle package ha
// balaye code e scanner asli ezafe mishe.


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\4\1\5\2\0\1\6\1\7\1\10\2\6\1\11"+
    "\1\12\1\6\1\12\1\13\1\14\1\15\11\16\1\0"+
    "\1\6\1\4\1\17\1\4\2\0\1\20\3\21\1\22"+
    "\1\21\21\23\1\24\2\23\1\6\1\25\2\6\1\26"+
    "\1\0\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\23\1\40\1\41\1\23\1\42\1\43"+
    "\1\44\1\23\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\24\1\53\1\23\1\6\1\54\1\6\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\4\3\2\5\17\6"+
    "\1\7\2\1\1\0\1\10\1\11\3\0\7\6\1\12"+
    "\14\6\1\13\1\14\1\0\2\10\1\0\1\15\7\6"+
    "\1\12\11\6\1\0\1\15\2\6\1\12\13\6\1\12"+
    "\10\6\1\12\5\6\1\12\2\6\1\12\26\6";

  private static int [] zzUnpackAction() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\207\0\264\0\341\0\207"+
    "\0\207\0\u010e\0\u013b\0\u0168\0\u0195\0\u01c2\0\u01ef\0\u021c"+
    "\0\u0249\0\u0276\0\u02a3\0\u02d0\0\u02fd\0\u032a\0\u0357\0\u0384"+
    "\0\u03b1\0\u03de\0\u040b\0\u0438\0\u0465\0\207\0\u0492\0\u04bf"+
    "\0\u04ec\0\u0519\0\u0546\0\u0573\0\u05a0\0\u05cd\0\u05fa\0\u0627"+
    "\0\u0654\0\u0681\0\u06ae\0\u06db\0\u0708\0\u05fa\0\u0735\0\u0762"+
    "\0\u078f\0\u07bc\0\u07e9\0\u0816\0\u0843\0\u0870\0\u089d\0\u08ca"+
    "\0\u08f7\0\u0924\0\207\0\u0951\0\u097e\0\207\0\u09ab\0\u09d8"+
    "\0\u05a0\0\u0a05\0\u0a32\0\u0a5f\0\u0a8c\0\u0ab9\0\u0ae6\0\u0b13"+
    "\0\u0a05\0\u0b40\0\u0b6d\0\u0b9a\0\u0bc7\0\u0bf4\0\u0c21\0\u0c4e"+
    "\0\u0c7b\0\u0ca8\0\u04bf\0\u09d8\0\u0cd5\0\u0d02\0\u0cd5\0\u0d2f"+
    "\0\u0d5c\0\u0d89\0\u0db6\0\u0de3\0\u0e10\0\u0e3d\0\u0e6a\0\u0e97"+
    "\0\u0ec4\0\u0ef1\0\u0ef1\0\u0f1e\0\u0f4b\0\u0f78\0\u0fa5\0\u0fd2"+
    "\0\u0fff\0\u102c\0\u1059\0\u102c\0\u1086\0\u10b3\0\u10e0\0\u110d"+
    "\0\u113a\0\u113a\0\u1167\0\u1194\0\u1194\0\u11c1\0\u11ee\0\u121b"+
    "\0\u1248\0\u1275\0\u12a2\0\u12cf\0\u12fc\0\u1329\0\u1356\0\u1383"+
    "\0\u13b0\0\u13dd\0\u140a\0\u1437\0\u1464\0\u1491\0\u14be\0\u14eb"+
    "\0\u1518\0\u1545\0\207";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\6\1\7\1\10\1\11\1\12\1\4"+
    "\1\7\1\13\1\11\1\14\1\15\1\16\1\7\1\17"+
    "\4\20\2\4\1\20\1\21\1\22\1\20\1\23\1\24"+
    "\2\20\1\25\1\20\1\26\1\27\1\20\1\30\1\31"+
    "\1\32\1\33\1\20\1\34\1\35\1\20\1\12\5\4"+
    "\1\36\17\4\1\37\34\4\1\36\17\4\1\40\27\4"+
    "\57\0\1\5\71\0\1\11\44\0\1\11\2\0\1\11"+
    "\41\0\1\11\7\0\1\11\2\0\1\11\4\0\1\11"+
    "\34\0\1\11\11\0\1\41\2\0\1\42\2\0\1\11"+
    "\50\0\1\43\1\0\2\16\3\0\1\44\1\0\1\45"+
    "\6\0\1\44\20\0\1\46\13\0\1\43\1\0\2\16"+
    "\3\0\1\44\10\0\1\44\20\0\1\44\15\0\2\47"+
    "\1\0\5\47\1\0\17\47\1\50\6\47\16\0\2\47"+
    "\1\0\5\47\1\0\26\47\16\0\2\47\1\0\5\47"+
    "\1\0\15\47\1\51\1\47\1\52\6\47\16\0\2\47"+
    "\1\0\5\47\1\0\13\47\1\53\1\47\1\54\10\47"+
    "\16\0\2\47\1\0\5\47\1\0\13\47\1\55\12\47"+
    "\16\0\2\47\1\0\5\47\1\0\11\47\1\56\3\47"+
    "\1\57\10\47\16\0\2\47\1\0\5\47\1\0\6\47"+
    "\1\56\5\47\1\60\11\47\16\0\2\47\1\0\5\47"+
    "\1\0\5\47\1\61\7\47\1\62\10\47\16\0\2\47"+
    "\1\0\5\47\1\0\5\47\1\63\20\47\16\0\2\47"+
    "\1\0\5\47\1\0\15\47\1\51\1\47\1\64\6\47"+
    "\16\0\2\47\1\0\5\47\1\0\5\47\1\65\7\47"+
    "\1\66\10\47\16\0\2\47\1\0\5\47\1\0\21\47"+
    "\1\67\4\47\16\0\2\47\1\0\5\47\1\0\10\47"+
    "\1\70\15\47\16\0\2\47\1\0\5\47\1\0\15\47"+
    "\1\71\10\47\16\0\2\47\1\0\5\47\1\0\10\47"+
    "\1\72\15\47\6\0\1\73\2\0\1\73\14\0\1\73"+
    "\14\0\1\73\2\0\1\73\1\0\1\73\4\0\1\73"+
    "\5\0\1\74\2\0\1\74\14\0\1\74\14\0\1\74"+
    "\2\0\1\74\1\0\1\74\4\0\1\74\11\41\1\75"+
    "\43\41\2\42\1\76\1\77\51\42\15\0\2\43\3\0"+
    "\1\44\10\0\1\44\20\0\1\44\12\0\1\100\41\0"+
    "\1\100\15\0\2\101\1\0\3\101\4\0\6\101\32\0"+
    "\1\100\2\0\2\101\1\0\3\101\4\0\6\101\17\0"+
    "\1\100\15\0\2\102\1\0\5\102\1\0\26\102\16\0"+
    "\2\102\1\0\5\102\1\0\17\102\1\103\6\102\16\0"+
    "\2\102\1\0\5\102\1\0\15\102\1\104\10\102\16\0"+
    "\2\102\1\0\5\102\1\0\5\102\1\105\20\102\16\0"+
    "\2\102\1\0\5\102\1\0\1\102\1\106\24\102\16\0"+
    "\2\102\1\0\5\102\1\0\14\102\1\107\11\102\16\0"+
    "\2\102\1\0\5\102\1\0\20\102\1\110\5\102\16\0"+
    "\2\102\1\0\5\102\1\0\17\102\1\111\6\102\16\0"+
    "\2\102\1\0\5\102\1\0\1\112\20\102\1\111\4\102"+
    "\16\0\2\102\1\0\5\102\1\0\14\102\1\111\4\102"+
    "\1\111\4\102\16\0\2\102\1\0\5\102\1\0\15\102"+
    "\1\113\10\102\16\0\2\102\1\0\5\102\1\0\24\102"+
    "\1\111\1\102\16\0\2\102\1\0\5\102\1\0\11\102"+
    "\1\114\14\102\16\0\2\102\1\0\5\102\1\0\1\102"+
    "\1\104\17\102\1\115\4\102\16\0\2\102\1\0\5\102"+
    "\1\0\6\102\1\111\17\102\16\0\2\102\1\0\5\102"+
    "\1\0\1\102\1\116\15\102\1\117\6\102\16\0\2\102"+
    "\1\0\5\102\1\0\5\102\1\120\20\102\16\0\2\102"+
    "\1\0\5\102\1\0\11\102\1\121\14\102\16\0\2\102"+
    "\1\0\5\102\1\0\11\102\1\122\14\102\26\0\1\123"+
    "\27\0\11\41\1\75\2\41\1\76\40\41\2\0\1\76"+
    "\67\0\2\124\53\0\2\125\1\0\5\125\1\0\26\125"+
    "\16\0\2\125\1\0\5\125\1\0\1\125\1\126\24\125"+
    "\16\0\2\125\1\0\5\125\1\0\13\125\1\127\12\125"+
    "\16\0\2\125\1\0\5\125\1\0\1\125\1\130\24\125"+
    "\16\0\2\125\1\0\5\125\1\0\20\125\1\131\5\125"+
    "\16\0\2\125\1\0\5\125\1\0\21\125\1\132\4\125"+
    "\16\0\2\125\1\0\5\125\1\0\5\125\1\127\20\125"+
    "\16\0\2\125\1\0\5\125\1\0\11\125\1\133\6\125"+
    "\1\134\5\125\16\0\2\125\1\0\5\125\1\0\16\125"+
    "\1\127\7\125\16\0\2\125\1\0\5\125\1\0\14\125"+
    "\1\135\11\125\16\0\2\125\1\0\5\125\1\0\22\125"+
    "\1\136\3\125\16\0\2\125\1\0\5\125\1\0\21\125"+
    "\1\137\4\125\16\0\2\125\1\0\5\125\1\0\11\125"+
    "\1\140\14\125\16\0\2\125\1\0\5\125\1\0\14\125"+
    "\1\127\11\125\16\0\2\125\1\0\5\125\1\0\4\125"+
    "\1\127\21\125\16\0\2\125\1\0\5\125\1\0\13\125"+
    "\1\141\12\125\16\0\2\142\1\0\5\142\1\0\26\142"+
    "\16\0\2\142\1\0\5\142\1\0\25\142\1\143\16\0"+
    "\2\142\1\0\5\142\1\0\12\142\1\143\13\142\16\0"+
    "\2\142\1\0\5\142\1\0\20\142\1\143\5\142\16\0"+
    "\2\142\1\0\5\142\1\0\11\142\1\144\14\142\16\0"+
    "\2\142\1\0\5\142\1\0\14\142\1\145\11\142\16\0"+
    "\2\142\1\0\5\142\1\0\21\142\1\146\4\142\16\0"+
    "\2\142\1\0\5\142\1\0\21\142\1\143\4\142\16\0"+
    "\2\142\1\0\5\142\1\0\17\142\1\147\6\142\16\0"+
    "\2\142\1\0\5\142\1\0\11\142\1\150\14\142\16\0"+
    "\2\142\1\0\5\142\1\0\14\142\1\151\11\142\16\0"+
    "\2\142\1\0\5\142\1\0\5\142\1\143\20\142\16\0"+
    "\2\152\1\0\5\152\1\0\26\152\16\0\2\152\1\0"+
    "\5\152\1\0\14\152\1\153\11\152\16\0\2\152\1\0"+
    "\5\152\1\0\21\152\1\154\4\152\16\0\2\152\1\0"+
    "\5\152\1\0\17\152\1\155\6\152\16\0\2\152\1\0"+
    "\5\152\1\0\14\152\1\154\11\152\16\0\2\152\1\0"+
    "\5\152\1\0\3\152\1\154\22\152\16\0\2\152\1\0"+
    "\5\152\1\0\7\152\1\154\16\152\16\0\2\156\1\0"+
    "\5\156\1\0\26\156\16\0\2\156\1\0\5\156\1\0"+
    "\22\156\1\157\3\156\16\0\2\156\1\0\5\156\1\0"+
    "\11\156\1\160\14\156\16\0\2\161\1\0\5\161\1\0"+
    "\26\161\16\0\2\161\1\0\5\161\1\0\5\161\1\162"+
    "\20\161\16\0\2\161\1\0\5\161\1\0\14\161\1\163"+
    "\11\161\16\0\2\164\1\0\5\164\1\0\26\164\16\0"+
    "\2\164\1\0\5\164\1\0\7\164\1\165\16\164\16\0"+
    "\2\166\1\0\5\166\1\0\26\166\16\0\2\167\1\0"+
    "\5\167\1\0\26\167\16\0\2\170\1\0\5\170\1\0"+
    "\26\170\16\0\2\171\1\0\5\171\1\0\26\171\16\0"+
    "\2\172\1\0\5\172\1\0\26\172\16\0\2\173\1\0"+
    "\5\173\1\0\26\173\16\0\2\174\1\0\5\174\1\0"+
    "\26\174\16\0\2\175\1\0\5\175\1\0\26\175\16\0"+
    "\2\176\1\0\5\176\1\0\26\176\16\0\2\177\1\0"+
    "\5\177\1\0\26\177\16\0\2\200\1\0\5\200\1\0"+
    "\26\200\16\0\2\201\1\0\5\201\1\0\26\201\16\0"+
    "\2\202\1\0\5\202\1\0\26\202\16\0\2\203\1\0"+
    "\5\203\1\0\26\203\16\0\2\204\1\0\5\204\1\0"+
    "\26\204\16\0\2\205\1\0\5\205\1\0\26\205\16\0"+
    "\2\206\1\0\5\206\1\0\26\206\16\0\2\207\1\0"+
    "\5\207\1\0\26\207\16\0\2\210\1\0\5\210\1\0"+
    "\26\210\16\0\2\211\1\0\5\211\1\0\26\211\16\0"+
    "\2\212\1\0\5\212\1\0\26\212\16\0\2\213\1\0"+
    "\5\213\1\0\26\213\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5490];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\2\11\2\1\2\11\24\1\1\11\2\1\1\0"+
    "\2\1\3\0\24\1\1\11\1\1\1\0\1\11\1\1"+
    "\1\0\22\1\1\0\67\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
     public class Token {
     String type;
     Object value;
     public Token(String type , Object value){
         this.value=value;
         this.type=type;
     }
 }
    //dakhele class e scanner ezafe misheh.
    // tarif e variable va function va class dar inja tarif mishavad.
    public int ICV;
    public double RCV;
    private StringBuffer string  = new StringBuffer();
    public String stringValue = "";


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':  // fall through
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { //    return "Error at line: "+yyline + "index: "+ yycolumn + "character = "+ yytext()  ;
     System.out.println("Error at line: "+yyline + "index: "+ yycolumn + "character = "+ yytext());
     return new Token("Undefined", yytext() ) ;
            }
            // fall through
          case 14: break;
          case 2:
            { 
            }
            // fall through
          case 15: break;
          case 3:
            { return new Token("Operators",yytext());
            }
            // fall through
          case 16: break;
          case 4:
            { yybegin(STRING);
        return new Token("String",yytext());
            }
            // fall through
          case 17: break;
          case 5:
            { ICV = Integer.parseInt(yytext());
        System.out.print("Number: "+ ICV + " ");
        return new Token("Integer",ICV);
            }
            // fall through
          case 18: break;
          case 6:
            { return new Token("Identifiers",yytext());
            }
            // fall through
          case 19: break;
          case 7:
            { string.append(yytext());
          stringValue = string.toString();
          string = new StringBuffer();
          yybegin(YYINITIAL);
          return new Token("String",stringValue);
            }
            // fall through
          case 20: break;
          case 8:
            { return new Token("Comment",yytext());
            }
            // fall through
          case 21: break;
          case 9:
            { return new Token("Real",yytext());
            }
            // fall through
          case 22: break;
          case 10:
            { return new Token("Reserved",yytext());
            }
            // fall through
          case 23: break;
          case 11:
            { string.append(yytext());
        return new Token("Special",yytext());
            }
            // fall through
          case 24: break;
          case 12:
            { string.append(yytext());
        return new Token("String",yytext());
            }
            // fall through
          case 25: break;
          case 13:
            { return new Token("Integer",yytext());
            }
            // fall through
          case 26: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
